[window.padding]
x = 8
y = 8


[scrolling]
history = 10000
multiplier = 3


[font]
size = 12
# size = 8

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "BoldItalic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "BoldItalic"


[colors.bright]
black = "0x9ea7b3"
blue = "0x91cbff"
cyan = "0x39c5cf"
green = "0x4ae168"
magenta = "0xcb9eff"
red = "0xffb1af"
white = "0xd9dee3"
yellow = "0xf7c843"

[colors.cursor]
cursor = "0xf0f3f6"
text = "0x0a0c10"

[colors.normal]
black = "0x7a828e"
blue = "0x71b7ff"
cyan = "0x39c5cf"
green = "0x26cd4d"
magenta = "0xcb9eff"
red = "0xff9492"
white = "0xd9dee3"
yellow = "0xf0b72f"

[colors.primary]
background = "0x0a0c10"
foreground = "0xf0f3f6"


[cursor.style]
shape = "Underline"
blinking = "On"
